SU-SWS/ace-sdssgryphon

blt/src/Blt/Plugin/Commands/GryphonCommands.php

- SDSS-1072: Added role report blt command
3. Verify...
[SDSS-1072](https://stanfordits.atlassian.net/browse/SDSS-1072): DEV | Create report of site managers on the stack
- [Browserstack](https://live.browserstack.com/dashboard) …

SDSS-1072: Added role report blt command

---

docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/templates/block/block--menu-block--newsroom.html.twig
docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/templates/page.html.twig

- Moved the `section` tag to better help a11y
- ASAP
- Normal
2. Navigate to news page.
3. Turn on the newsroom menu and add links
4. Verify the moved tags. 
5. Verify it works reponsively.
[- SDSS-1244](https://stanfordits.atlassian.net/browse/SDSS-1244)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

SDSS-1244: fine tuning a11y fix

---

.ddev/config.yaml

- Updated ddev to 8.2 and removed hooks.
- Soon

DEVOPS-000 - DDev PHP 8.2 and removinghooks

---

docroot/profiles/sdss/sdss_profile/config/sync/core.entity_form_display.config_pages.stanford_local_footer.default.yml
docroot/profiles/sdss/sdss_profile/config/sync/core.entity_view_display.config_pages.stanford_local_footer.default.yml
docroot/profiles/sdss/sdss_profile/tests/codeception/acceptance/LocalFooter/LocalFooterCest.php

- Removed Content Block 4 from the Local Footer config file.
- When time allows
Normal
2. Import configs
3. Navigate to Local Footer Config
4. Verify there isn't a Fourth Content block
[- SDSS-1235](https://stanfordits.atlassian.net/browse/SDSS-1235)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/SWS/External+Account+Credentials)

SDSS-1235: local footer config update

---

docroot/profiles/sdss/sdss_profile/config/sync/views.view.stanford_person.yml

- SDSS groups need the ability to use additional filters for People. I added Research Topics, Organization, Focal Areas, and Shared Tags.
Sidenote: this list still has depth of 1. Wondering if that is OK, or if we want to add?
- Next release
- Important, but not on fire
1. Check out this  branch
2. Make some people
3. Tag by Shared Tags, Org, or Research topics
4. Put a Lists Paragraph on a Basic Page
5. Filter by one of these terms
- Other PRs
- …

SDSS-1252: Adding additional terms to contextual filter for people

---

docroot/profiles/sdss/sdss_profile/config/sync/field.field.node.stanford_page.field_menulink.yml
docroot/profiles/sdss/sdss_profile/config/sync/node.type.stanford_page.yml

- Allow Basic Pages to be placed in News & Research menu from the node edit form (rather than making them custom menu items, which can be problematic for internal content)
- Anytime! This is a teensy one!
- Moderately important as I'd prefer other sites on the stack use the usual methods for adding pages to a menu if they use this feature.
2. Make a new Basic Page
3. Place it in the News & Research menu
4. Save
- Other PRs
- …

SDSS-1265: Allow adding Basic Pages to Newsroom Menu from Edit Node form

---

docroot/profiles/sdss/sdss_profile/config/sync/views.view.stanford_events.yml

- This redoes the work of adding the Localist taxonomies to the card and list displays for the Lists Paragraph. It also consolidates the filters since the additional filters were NOT working with the Lists Paragraph.
- Soon, so it doesn't go stake again!
- This work is in two tickets, so would like to get it done for all!
2. Import some Localist events
3. Make a Basic Page
4. Try to filter events down using Subject, Audience, or Keyword/Tags from localist.
5. Try with Card and List view to be sure
- Other PRs
- Anyone who should be …

SDSS-252: Allow Events List paragraph to be filtered by multiple taxonomies

---

docroot/profiles/sdss/sdss_profile/config/sync/views.view.stanford_news.yml

-  To make a view of Media Mentions that uses the same checkbox that is used to exclude them elsewhere. Clare needs a list (not card) view with a Load More
- Next release
- Medium
2. Make sure you have news that have that Media Mentions box tagged
3. Add it to a page to make sure it works. 
4. Ideally add more than 24 so you can see it in action with load more (I use Devel Generate for this.)
- Other PRs
- [Accessibility Manual …

SDSS-1220: Add Media Mentions list display to News list paragraph

---

docroot/profiles/sdss/sdss_profile/sdss_profile.install

- Update hook to uninstall the earth_news_importer
3. Verify...
https://stanfordits.atlassian.net/browse/SDSS-1255
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack …

SDSS-1255: Uninstall earth_news_importer

---

docroot/profiles/sdss/sdss_profile/sdss_profile.install

- Earth News Importer uninstall update hook fixup
3. Verify...
https://stanfordits.atlassian.net/browse/SDSS-1255
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack …

SDSS-1255: Earth News Importer uninstall update hook fixup

---

composer.lock
docroot/profiles/sdss/sdss_profile/config/sync/stanford_samlauth.settings.yml

- Updated stanford_samlauth module
3. Verify...
https://stanfordits.atlassian.net/browse/SDSS-1271
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack …

SDSS-1271: Updated stanford_samlauth module

---

CHANGELOG.md
composer.lock
docroot/profiles/sdss/sdss_profile/config/sync/stanford_samlauth.settings.yml
docroot/profiles/sdss/sdss_profile/sdss_profile.info.yml
docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/sdss_subtheme.info.yml

Backtodev 4.3.3

---

docroot/profiles/sdss/sdss_profile/config/sync/search_api.index.full_site_content.yml
docroot/profiles/sdss/sdss_profile/config/sync/views.view.search.yml

- Enable searching by title.
- This will fix the extremely flaky search result test
3. Verify...
https://stanfordits.atlassian.net/browse/SDSS-1272
- [Browserstack](https://live.browserstack.com/dashboard) and link to …

SDSS-1272: Enable search by title

---

docroot/profiles/sdss/sdss_profile/config/sync/search_api.index.full_site_content.yml
docroot/profiles/sdss/sdss_profile/config/sync/views.view.search.yml

- Removes everything with the Media Mention checkbox from search results
- Next release
- Nice to have
2. Add some news with media mentions box checked and other non-media mentions content
3. Reindex search
4. Search and make sure you don't see them
- Other PRs
- [HTML …

SDSS-1266: Excluded Media Mention News from Site Search

---

docroot/profiles/sdss/sdss_profile/config/sync/core.extension.yml
docroot/profiles/sdss/sdss_profile/sdss_profile.install

- Disabled `page_cache` module
- See: https://stanfordits.atlassian.net/browse/SDSS-1218
3. Verify...
- Other PRs
- [Accessibility Manual Test …

SDSS-1218: Disabled page_cache module

---

docroot/profiles/sdss/sdss_profile/config/sync/views.view.news_research_search.yml

- Have media mentions filtered out of News search
- Next release
- Medium
2. Populate with a ton of news, some media mentions, some not
3. Reindex the search
4. Search using the news search. Makes sure there are no media mentions there.
- Other PRs
- …

SDSS-1266: Excluded Media Mention News from Newsroom Search

---

.github/workflows/deploy_branch.yml
.github/workflows/tests.yml
docroot/sites/settings/global.settings.php

SDSS-1256: Actions cleanup and added matrix for testing

---

docroot/profiles/sdss/sdss_profile/themes/stanford_profile_admin_theme/css/admin.css
docroot/profiles/sdss/sdss_profile/themes/stanford_profile_admin_theme/stanford_profile_admin_theme.info.yml
docroot/profiles/sdss/sdss_profile/themes/stanford_profile_admin_theme/stanford_profile_admin_theme.libraries.yml

- Added an `admin.css` CSS file to stanford_profile_admin_theme and hid the paragraph custom h2/h3 heading fields
3. Verify...
https://stanfordits.atlassian.net/browse/SDSS-1286
- …

SDSS-1286: Add CSS to stanford_profile_admin_theme and hide heading fields

---

docroot/profiles/sdss/sdss_profile/themes/stanford_profile_admin_theme/css/admin.css

- Removed the heading choice for the top banner and banner paragraph from the authoring.
- Shortened the selectors where possible.
- Added more comments.
- ASAP
- Normal
2. Navigate to a basic page and build a card and top banner and banner paragraph
3. Verify the heading choices are not available. 
4. Verify no changes to the end display.
[- SDSS-1286](https://stanfordits.atlassian.net/browse/SDSS-1286)
- [Browserstack](https://live.browserstack.com/dashboard) …

SDSS-1286: Fixup for banner heading choice. 

---

docroot/profiles/sdss/sdss_profile/src/Plugin/InstallTask/SiteSettings.php

SDSS-1294: Fix logger syntax in installtask

---

docroot/sites/sites.php

- The Tech Transfer for Defense site has been copied from `hackingfordefense` to `techtransferfordefense`.
- The URL should no longer be pointed to `hackingfordefense` and does not need to be pointed manually since the URL matches the alias.
3. Verify...
https://stanfordits.atlassian.net/browse/SDSS-1253
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmq …

SDSS-1253: Unpoint techtransferfordefense from hackingfordefense

---

docroot/profiles/sdss/sdss_profile/config/sync/core.entity_view_display.node.stanford_news.default.yml

- Media Mentions do not have images, and they do not keep users on the site. Josie would prefer they not show up in Explore More. 
- Next release
- 1
2. Create some news articles
3. Mark some as media mentions using the checkbox
4. Make sure they are all published
5. Look at an individual article and confirm that you don't see media mentions in the selection of three items at the bottom of the page
- Other PRs
- [Accessibility …

SDSS-1288: Exclude Media Mentions from Explore More on News

---

docroot/profiles/sdss/sdss_profile/config/sync/views.view.rss_feeds.yml
docroot/sites/blt.development.services.yml

- In the RSS feed, include the publication information if the source is not internal to SDSS. 
- Next release
- Low
2. Disable the twig formatting stuff
3. Make some news items with News Sources
4. The News Source is printed in the RSS feed at /rss/sdss-news-this-week in italics
5. If there is no news source, it does not appear
6. Use Mailchimp to send something out (Not really needed for testing... Aaron and I did that.)
- This affects the newsletter for Sustainability
- 
- [SDSS-1291](https://stanfordits.atlassian.net/browse/SDSS-1291)
- @aaroncole 
- Mailchimp SDSS This Week
- [Accessibility Manual Test Script](https://docs.google.com/document/d/1ZXJ9RIUNXsS674ow9j3qJ2g1OAkCjmqMXl0Gs8XHEPQ/edit?usp=sharing …

SDSS-1291: Label articles in RSS feed with external source

---

docroot/profiles/sdss/sdss_profile/sdss_profile.info.yml
docroot/profiles/sdss/sdss_profile/src/Plugin/InstallTask/SiteSettings.php
docroot/profiles/sdss/sdss_profile/tests/src/Kernel/Plugin/InstallTask/SiteSettingsTest.php
docroot/profiles/sdss/sdss_profile/tests/src/Unit/Plugin/HelpSection/ProfileConnectSectionTest.php
docroot/profiles/sdss/sdss_profile/tests/src/Unit/Plugin/HelpSection/ProfileHelpSectionTest.php
docroot/profiles/sdss/sdss_profile/tests/src/Unit/Plugin/HelpSection/ProfileResourceSectionTest.php

SDSS-1296: DEV | Update sdss_profile InstallTasks

SDSS-1296: Update SDSS profile installation

---

docroot/profiles/sdss/sdss_profile/config/sync/config_ignore.settings.yml
docroot/sites/settings/global.settings.php

- Turns off read-only status for 
- July 21
1. Read code
2. Or test on your local by copying two arrays from global.settings.php file: `$settings['config_readonly']` and
`$settings['config_readonly_whitelist_patterns']`
3. Clear cache and go to `admin/config/services/sdss-news-sharing`
- Other PRs
- [AMP …

FIXUP - turn off readonly for news sharing form

---

docroot/sites/sites.php

- Hard codes the domain name to the proper directory.
- July 30
1. Review code

SDSS-1307 - sites file for esos

---

docroot/profiles/sdss/sdss_profile/config/sync/views.view.stanford_events.yml

- Allows Woods to filter events by Focal Area
- Everyone else gets it too!
- Aug 31
- Medium
2. Make some events
3. Tag some stuff with focal areas
4. Use the list paragraph with the appropriate argument in focal area (Card Disply + List Display)
5. Hopefully just get your tagged items!
No front-end impact to this PR
- [ N/A] Are the naming conventions following our standards?
- [ N/A] Does the code have sufficient inline comments?
- [ NO] Is there anything in this code that would be hidden or hard to discover through the UI?
- [NO ] Are there any [code smells](https://blog.codinghorror.com/code-smells/)?
- [ NO] Are tests provided? eg (unit, behat, or codeception)
- [N/A ] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizin …

SDSS-1342: Allow Event Lists to be filtered by focal areas

---

docroot/profiles/sdss/sdss_profile/config/sync/migrate_plus.migration.sdss_news_sharing.yml

- Added publishing_date to source id for news sharing migration
https://stanfordits.atlassian.net/browse/SDSS-1335

SDSS-1135: Added publishing_date to source id for news sharing migration

---

docroot/profiles/sdss/sdss_profile/sdss_profile.install

- Set Featured Events default value for existing content

SDSS-1360: DEV | Set Featured Events default value for existing content

---

docroot/profiles/sdss/sdss_profile/sdss_profile.install

- Set Explore More Options default for existing content

SDSS-1359: Set Explore More Options default for existing content

---

composer.lock

- Updated `colorbox` module to fix issue with `drupal-patches` patch not applying cleanly and causing fatal errors.
[SDSS-1364](https://stanfordits.atlassian.net/browse/SDSS-1364): BUG | Class "PlainTextOutput" not found error
[SDSS-1365](https://stanfordits.atlassian.net/browse/SDSS-1365): DEV | Upgrade colorbox module to 2.1.1
[SDSS-1364]: https://stanfordits.atlassian.net/browse/SDSS-1364?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SDSS-1365]: https://stanfordits.atlassian.net/browse/SDSS-1365?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SDSS-1365: Update colorbox module to v2.1.1

---

composer.json
composer.lock

- Consolidated drupal-patches into SDSS
https://stanfordits.atlassian.net/browse/SDSS-1366

SDSS-1366: Consolidated drupal-patches into SDSS

---

composer.json
composer.lock
docroot/profiles/sdss/sdss_profile/config/sync/auto_entitylabel.settings.node.stanford_person.yml
docroot/profiles/sdss/sdss_profile/config/sync/auto_entitylabel.settings.node.stanford_policy.yml
docroot/profiles/sdss/sdss_profile/config/sync/auto_entitylabel.settings.node.stanford_publication.yml
docroot/profiles/sdss/sdss_profile/config/sync/core.extension.yml
docroot/profiles/sdss/sdss_profile/config/sync/graphql.settings.yml

- Routine maintenance
[SDSS-1362](https://stanfordits.atlassian.net/browse/SDSS-1362): DEV | 4.6.2 maintenance and updates
[SDSS-1362]: https://stanfordits.atlassian.net/browse/SDSS-1362?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SDSS-1362: Routine maintenance

---

docroot/profiles/sdss/sdss_profile/config/sync/seckit.settings.yml
docroot/profiles/sdss/sdss_profile/config/sync/views.view.events_this_week.yml

- Drop featured filter from events this week RSS feed view
- https://stanfordits.atlassian.net/browse/SDSS-1374

SDSS-1374: Drop featured filter from events this week RSS feed view

---

composer.json
composer.lock

- Fixes the release of stanford_earth_r25 updates.
- ASAP
- Not critical but would like to have it on sdssrooms-test.stanford.edu for testing as soon as possible.
- ksharp will test

SDSS-1376: Update stanford_earth_r25 to v8.1.14

---

docroot/profiles/sdss/sdss_profile/config/sync/field.field.node.stanford_news.su_sdss_imported_news_sharing.yml
docroot/profiles/sdss/sdss_profile/sdss_profile.install

- Set default value for Imported via News Sharing field
https://stanfordits.atlassian.net/browse/SDSS-1377

SDSS-1377: Set default value for Imported via News Sharing field

---

docroot/profiles/sdss/sdss_profile/config/sync/search_api.index.full_site_content.yml

- Update `search_api` index processors to better handle URL's in text
https://www.drupal.org/project/search_api/issues/3069515#comment-15811683

Update search_api index processors to better handle URL's in text

---

docroot/profiles/sdss/sdss_profile/config/sync/field.field.node.stanford_event.su_sdss_featured.yml
docroot/profiles/sdss/sdss_profile/sdss_profile.install

- Set default value for Featured field
https://stanfordits.atlassian.net/browse/SDSS-1379

SDSS-1379: Set default value for Featured field

---

docroot/profiles/sdss/sdss_profile/config/sync/image.style.stanford_circle.yml

- SDSS-1394: Update stanford_circle image style image mask file path
- Bug fix for: https://stanfordits.atlassian.net/browse/SDSS-1394

SDSS-1394: Update stanford_circle image style image mask file path

---

README.md

Adds a note to the Gitpod setup instructions about setting up the GITCONFIG user variable to prevent conflicts with dev packages.
1. Check out this branch.
2. Follow the updated Gitpod setup instructions.
3. Verify that Gitpod is able to install and run the site.
- Other PRs …

SDSS-1426 | Update Gitpod setup documentation

---

docroot/profiles/sdss/sdss_profile/modules/sdss_news_sharing/src/Form/NewsSharingSettingsForm.php

This adds a link to the Website User Guide News Sharing section in the News Sharing Settings page Source URLs field help text.
2. Navigate to `/admin/config/importers/sdss-news-sharing`
3. Verify that the Source URLs field help text is, "Enter the full source URL of the SDSS site to pull from, including the terms. More information available at [Website User Guide - News Sharing](https://sdssuserguide-prod.stanford.edu/configure/content-importers/news-sharing)".
- Other PRs
- [AMP …

SDSS-1332 | Enhance help text for News Sharing

---

composer.json
composer.lock
docroot/profiles/sdss/sdss_profile/config/sync/core.entity_view_display.node.stanford_news.teaser.yml
docroot/profiles/sdss/sdss_profile/config/sync/core.extension.yml
docroot/profiles/sdss/sdss_profile/config/sync/editoria11y.settings.yml
docroot/profiles/sdss/sdss_profile/config/sync/user.role.authenticated.yml
docroot/profiles/sdss/sdss_profile/config/sync/user.role.site_builder.yml
docroot/profiles/sdss/sdss_profile/config/sync/user.role.site_developer.yml
docroot/profiles/sdss/sdss_profile/config/sync/user.role.site_manager.yml
docroot/profiles/sdss/sdss_profile/tests/codeception/acceptance/LocalFooter/LocalFooterCest.php

[SDSS-1450](https://stanfordits.atlassian.net/browse/SDSS-1450): DEV | 4.7.4 maintenance and updates
- Package updates.
[SDSS-1450]: https://stanfordits.atlassian.net/browse/SDSS-1450?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SDSS-1450: 4.7.4 Routine Maintenance

---

docroot/profiles/sdss/sdss_profile/config/sync/field.field.node.stanford_news.su_sdss_news_banner_caption.yml
docroot/profiles/sdss/sdss_profile/config/sync/field.field.node.stanford_news.su_sdss_news_dek_long.yml
docroot/profiles/sdss/sdss_profile/config/sync/field.field.node.stanford_person.su_sdss_person_alt_bio.yml
docroot/profiles/sdss/sdss_profile/config/sync/field.field.node.stanford_person.su_sdss_person_alt_title.yml
docroot/profiles/sdss/sdss_profile/config/sync/field.field.node.stanford_person.su_sdss_person_research_state.yml
docroot/profiles/sdss/sdss_profile/config/sync/field.field.paragraph.callout_quote.su_callout_author.yml
docroot/profiles/sdss/sdss_profile/config/sync/field.field.paragraph.callout_quote.su_callout_author_title.yml
docroot/profiles/sdss/sdss_profile/config/sync/field.field.paragraph.callout_quote.su_callout_quote.yml
docroot/profiles/sdss/sdss_profile/config/sync/field.field.paragraph.editorial_sidebar.su_sidebar_body.yml
docroot/profiles/sdss/sdss_profile/config/sync/field.field.paragraph.editorial_sidebar.su_sidebar_title.yml

Add filter_format dependencies

---

docroot/profiles/sdss/sdss_profile/config/sync/views.view.sdss_news_sharing.yml

- For special characters needed to adjust the `title` and `dek` fields to output raw values, otherwise they are encoded and import incorrectly (e.g., `&amp;`, `&quot;`, etc.,)
3. Verify...
https://stanfordits.atlassian.net/browse/SDSS-1350
- [HTML …

SDSS-1350: Adjusted News Sharing feed fields to raw output

---

composer.json
composer.lock
docroot/profiles/sdss/sdss_profile/modules/stanford_profile_helper/modules/stanford_decoupled/src/Plugin/Next/Revalidator/RedirectPath.php
docroot/profiles/sdss/sdss_profile/modules/stanford_profile_helper/modules/stanford_decoupled/tests/src/Kernel/Plugin/Next/Revalidator/RedirectPathTest.php
docroot/profiles/sdss/sdss_profile/tests/codeception/functional/Users/RolesCest.php

- Routine maintenance
- Updated dependencies
[SDSS-1507](https://stanfordits.atlassian.net/browse/SDSS-1507): DEV | 4.10.1 maintenance and updates
[SDSS-1507]: https://stanfordits.atlassian.net/browse/SDSS-1507?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SDSS-1507: Routine maintenance

---

blt/src/Blt/Plugin/Commands/GryphonAcquiaApiCommands.php

Update code for getting Acquia API access token in blt commands

Update code for getting Acquia API access token in blt commands

---

docroot/profiles/sdss/sdss_profile/config/sync/field.field.config_pages.stanford_person_importer.su_person_orgs.yml
docroot/profiles/sdss/sdss_profile/config/sync/views.view.cap_orgs.yml
docroot/profiles/sdss/sdss_profile/modules/stanford_profile_helper/modules/stanford_person/modules/stanford_person_importer/src/Cap.php
docroot/profiles/sdss/sdss_profile/modules/stanford_profile_helper/modules/stanford_person/modules/stanford_person_importer/stanford_person_importer.install

[SDSS-1515](https://stanfordits.atlassian.net/browse/SDSS-1515): Update CAP importer to handle large org code arrays
Relevant PR's:
- https://github.com/SU-SWS/stanford_profile_helper/pull/402
- https://github.com/SU-SWS/stanford_profile/pull/930
1. Review code
[SDSS-1515]: https://stanfordits.atlassian.net/browse/SDSS-1515?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SDSS-1515: Update CAP importer to handle large org code arrays

---

composer.json
composer.lock
docroot/profiles/sdss/sdss_profile/sdss_profile.info.yml

[SDSS-1518](https://stanfordits.atlassian.net/browse/SDSS-1518): Add Better Exposed Filters module
Added and enabled the `better_exposed_filters` module.
[SDSS-1518]: https://stanfordits.atlassian.net/browse/SDSS-1518?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SDSS-1518: Add and enable Better Exposed Filters module

---

README.md
docs/development-requirements.md
docs/new-site-provision.md

Added provisioning and requirements documentation

Added provisioning and requirements documentation

---

docroot/profiles/sdss/sdss_profile/config/sync/views.view.events_this_week.yml
docroot/profiles/sdss/sdss_profile/config/sync/views.view.rss_feeds.yml

RSS Feed adjustments. See tickets.
Includes two tickets:
- [SDSS-1489](https://stanfordits.atlassian.net/browse/SDSS-1489): Add date and time for events to the This Week newsletter
- [SDSS-1509](https://stanfordits.atlassian.net/browse/SDSS-1509): Create an all news RSS feed
[SDSS-1489]: https://stanfordits.atlassian.net/browse/SDSS-1489?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SDSS-1509]: https://stanfordits.atlassian.net/browse/SDSS-1509?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SDSS-1489, SDSS-1509: Create All News feed and add date/time to News This Week feed

---

.github/workflows/acquia_cleanup.yml
.github/workflows/copy_dbs_to_staging.yml
blt/src/Blt/Plugin/Commands/GryphonAcquiaApiCommands.php

Added git workflow and blt commands to:
- Delete manual database backups on all Acquia environments older than 120 days
- Delete non-active git tags and branches on Acquia older than 1 year
References
- https://github.com/SU-HSDO/suhumsci/blob/develop/.github/workflows/acquia-cleanup.yml
- https://github.com/SU-HSDO/suhumsci/blob/5d10cdf98df2c7305a3683d627a859650552c73d/blt/src/Blt/Plugin/Commands/HsAcquiaApiCommands.php#L161
- https://github.com/SU-HSDO/suhumsci/blob/5d10cdf98df2c7305a3683d627a859650552c73d/blt/src/Blt/Plugin/Commands/HsAcquiaApiCommands.php#L442
Review code.

Added database and branch clean-up workflows

---

composer.json
composer.lock

- New version of room reservations module

SDSS-0000: Update stanford_earth_r25 room reservation module to 8.1.15.

---

composer.json
composer.lock

- Bug fixes for Room Reservations for Farm and Press Building
- In time for 7/16 release.

Update room reservations module to latest version.

---

composer.json
composer.lock

SDSS-0000: Room reservation fixups

---

composer.lock
patches/contrib/views_taxonomy_term_name_depth-mr-2.patch

Resolves widespread 502 errors by updating the `views_taxonomy_term_name_depth` module to 7.3.1 and applying the latest patch to support multiple value queries. This fixes invalid query conditions that caused outages on multiple SDSS multi-site pages.
ASAP
9/10. This affects multiple sites and products, causing critical outages and temporary unavailability.
1. Check out the `main` branch and ensure your environment is up to date.
2. Sync the Epsci site (site alias: `gs`):
```bash
blt drupal:sync --site=gs
```
3. Visit the following URLs and confirm that 502 errors are present:
- /research-impact/planetary-science/planetary-science-news
- /research-impact/planetary-science/planetary-science-events
- /research-impact/planetary-science/planetary-science-events/past-planetary-science-events …

Updated views_taxonomy_term_name_depth module and multiple value patch

---

CHANGELOG.md
composer.lock
docroot/profiles/sdss/sdss_profile/sdss_profile.info.yml
docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/sdss_subtheme.info.yml
patches/contrib/views_taxonomy_term_name_depth-mr-2.patch

Backtodev 4.12.2

---

composer.lock

| Production Changes                 | From    | To      | Compare                                                                                       |
|------------------------------------|---------|---------|-----------------------------------------------------------------------------------------------|
| consolidation/annotated-command    | 4.10.1  | 4.10.2  | [...](https://github.com/consolidation/annotated-command/compare/4.10.1...4.10.2)             |
| drupal/acquia_connector            | ef8c8b0 | ec2468e | [...](https://git.drupalcode.org/project/acquia_connector/-/compare/ef8c8b0...ec2468e)        |
| drupal/consumers                   | 1.19.0  | 1.20.0  | [...](https://git.drupalcode.org/project/consumers/-/compare/1.19.0...1.20.0)                 |
| …

SDSS-1541: Routine maintenance

---

docroot/profiles/sdss/sdss_profile/sdss_profile.info.yml
docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/sdss_subtheme.info.yml

backtodev-4.13.0

---

composer.json
composer.lock

- Final set of room reservation updates for Stanford Farm

SDSS-0000: Update room reservation module to 8.1.22

---

.github/pull_request_template.md

[SDSS-1565](https://stanfordits.atlassian.net/browse/SDSS-1565): Clean up Pull Request Template
[SDSS-1565]: https://stanfordits.atlassian.net/browse/SDSS-1565?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SDSS-1565: Pull request template changes

---

docroot/sites/sites.php

[SDSS-1562](https://stanfordits.atlassian.net/browse/SDSS-1562): Launch | Sustainability Pathways Internships 9/18/25
[SDSS-1562]: https://stanfordits.atlassian.net/browse/SDSS-1562?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SDSS-1562: Point ssip.stanford.edu to sustainpathways site
