SU-SWS/ace-sdssgryphon

docroot/profiles/sdss/sdss_profile/config/sync/views.view.stanford_person.yml
- changed the number of people on initial load from 39 to 36 to be divisible by 4.
- Soon
- normal
2. Import the config
3. Navigate to to the content page and create 50+ people
4. Go to the `/people` page and verify there are only 36 people listed and no widows.
[- SDSS-359](https://stanfordits.atlassian.net/browse/SDSS-359)
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack …
=> SDSS-359: number of people on initial load of view page

docroot/profiles/sdss/sdss_profile/modules/sdss_layout_paragraphs/src/Plugin/Layout/SdssLayoutParagraphBase.php, docroot/profiles/sdss/sdss_profile/sdss_profile.install, docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/sdss_subtheme.react_behaviors.yml, docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/src/scss/components/row-backgrounds/_component-overrides.scss
- Removed the white background option from layouts.
- as time allows
- normal
2. Navigate to to a new page.
3. Create a row. 
4. Verify you can no longer add a white background to a row. 
- Other PRs
- …
=> SDSS-1268: Removed the white option for row backgrounds

docroot/profiles/sdss/sdss_profile/modules/sdss_layout_paragraphs/layouts/one_column/one-column.css, docroot/profiles/sdss/sdss_profile/modules/sdss_layout_paragraphs/layouts/two_column/two-column.css, docroot/profiles/sdss/sdss_profile/modules/sdss_layout_paragraphs/src/Layouts/OneColumn.php, docroot/profiles/sdss/sdss_profile/modules/sdss_layout_paragraphs/src/Layouts/OneFourOne.php, docroot/profiles/sdss/sdss_profile/modules/sdss_layout_paragraphs/src/Layouts/ThreeColumn.php, docroot/profiles/sdss/sdss_profile/modules/sdss_layout_paragraphs/src/Layouts/TwoColumn.php, docroot/profiles/sdss/sdss_profile/modules/sdss_layout_paragraphs/src/Plugin/Layout/SdssLayoutParagraphBase.php
- Removed width options from SDSS layout paragraphs.
- Also resolves bug in SDSS-835
ASAP
2. Create a new Basic Page
3. Add a new section / layout paragraph
4. Confirm the width options are gone
5. Add a 2 column layout paragraph
6. Add a paragraph into the right column
7. Switch the 2 column layout to a 1 column layout
8. Confirm the UI/form asks what region you want to move the existing paragraphs into (Move orphaned items)
https://stanfordits.atlassian.net/browse/SDSS-1298
https://stanfordits.atlassian.net/browse/SDSS-835
=> SDSS-1305: Remove width options from SDSS layout paragraphs

composer.json, composer.lock, docroot/profiles/sdss/sdss_profile/config/sync/config_ignore.settings.yml, tests/phpunit/example.phpunit.xml
[SDSS-1270](https://stanfordits.atlassian.net/browse/SDSS-1270): DEV | Deprecate and remove earth_news_importer
[SDSS-1270]: https://stanfordits.atlassian.net/browse/SDSS-1270?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SDSS-1270: Deprecate and fully remove earth_news_importer

docroot/profiles/sdss/sdss_profile/config/sync/core.entity_form_display.node.stanford_event.default.yml, docroot/profiles/sdss/sdss_profile/config/sync/core.entity_view_display.node.stanford_event.default.yml, docroot/profiles/sdss/sdss_profile/config/sync/core.entity_view_display.node.stanford_event.search_indexing.yml, docroot/profiles/sdss/sdss_profile/config/sync/core.entity_view_display.node.stanford_event.stanford_card.yml, docroot/profiles/sdss/sdss_profile/config/sync/core.entity_view_display.node.stanford_event.teaser.yml, docroot/profiles/sdss/sdss_profile/config/sync/field.field.node.stanford_event.su_sdss_featured.yml, docroot/profiles/sdss/sdss_profile/config/sync/field.storage.node.su_sdss_featured.yml, docroot/profiles/sdss/sdss_profile/config/sync/views.view.events_this_week.yml, docroot/profiles/sdss/sdss_profile/tests/codeception/acceptance/Content/EventsCest.php
- Allow SDSS to have two event feeds for Mailchimp, one for featured events and one without featured events
- August 31
HIGH
2. Create some events in the future
3. Mark a couple as featured using the checkbox at the top of the form
4. Check that featured events show up here: rss/featured-events-this-week
5. Check that no featured events show up:  /rss/events-this-week
NO FRONT END
- [ YES] Are the naming conventions following our standards?
- [ YES]  Does the code have sufficient inline comments?
- [ NOPE]  Is there anything in this code that would be hidden or hard to discover through the UI?
- [ NO] Are all [forms properly sanitized](https://www.drupal.org/docs/8/security/drupal-8-sanitizing-output)?
- [ NO ] Any obvious [security flaws or new areas for …
=> SDSS-1300: Featured Events This Week

docroot/profiles/sdss/sdss_profile/config/sync/field.storage.node.su_sdss_related_content.yml, docroot/profiles/sdss/sdss_profile/tests/codeception/acceptance/Content/BasicPageCest.php, docroot/profiles/sdss/sdss_profile/tests/codeception/acceptance/Content/PublicationsCest.php
- Adjust permissions for the Related Content field so that it has the same permissions as the content types associated with it
- Not required for release of Explore More, so could wait until next release
Medium
2. Change yourself to a site manager or site editor
3. Try to use the field
No Front-end impact
Not much new here either!
All good!
- [ NOPE] Is there anything included in this PR that is not related to the problem it is trying to solve?
- [YES  ] Is the approach to the problem appropriate?
- News
- SDSS-1299
- …
=> SDSS-1358: Allow all editors to use Related Content field

composer.json, patches/contrib/colorbox-mr-14.patch, patches/contrib/default_content-mr-15.patch, patches/contrib/diff-mr-42.patch, patches/contrib/field_encrypt-mr-31.patch, patches/contrib/menu_link-mr-8.patch, patches/contrib/menu_link-mr-9.patch, patches/contrib/menu_link_weight-mr-2.patch, patches/contrib/response_code_condition-mr-2.patch, patches/contrib/views_taxonomy_term_name_depth-mr-2.patch, patches/contrib/webp-mr-33.patch
- Deprecated and updated inclusion of Drupal merge request patches
- Following [Drupal Recommendation](https://www.drupal.org/docs/develop/git/using-gitlab-to-contribute-to-drupal/downloading-a-patch-file) to download patches from merge requests instead of linking to them directly.
https://stanfordits.atlassian.net/browse/SDSS-1367
=> SDSS-1367: Deprecated and updated inclusion of Drupal merge request patches

docroot/profiles/sdss/sdss_profile/config/sdssrooms/block.block.stanford_basic_pagetitle.yml
- block.stanford_basic.pagetitle was hiding the page title for calendar pages. we now want to show the page titles.
- ASAP. Before next release if possible.
- Not critical, but I have to manually update the block after every production release.
=> SDSS-1376: Remove "/r25/*/calendar" from block.stanford_basic.pagetitle

composer.json, composer.lock
- Updates stanford_earth_r25 module from 8.1.12 to 8.1.13
- Next feasible code update.
- Not critical, but adds feature for Hartley reservations needed by SDSS Dean's Office staff
- Let Kassie Sharp know when build is available on https://sdssrooms-test.stanford.edu and Kassie will test
=> SDSS-1376: Update stanford_earth_r25 module to 8.1.13

composer.json, composer.lock, patches/stanford/stanford_migrate-placeimg-test-fix.patch, tests/phpunit/example.phpunit.xml
- Added a patch to fix PHP Unit test failures. Remove [the defunct placeimg URL test is fixed](https://github.com/SU-SWS/stanford_migrate/blob/d695c0278128b811fecfab05283c04387318237a/tests/src/Unit/Plugin/migrate/process/StanfordFileImportTest.php#L58)
=> SDSS-000: Add patch to remove defunct placeimg URL from unit test

docroot/profiles/sdss/sdss_profile/sdss_profile.install
- Set the default value for explore more picker field where it's not set
- This is a fix for a previous update which only updated the first batch of nodes because it was missing the `&$sandbox` parameter in the hook to keep batching.
https://stanfordits.atlassian.net/browse/SDSS-1378
=> SDSS-1378: FIX | Set default value for explore more picker

docroot/profiles/sdss/sdss_profile/config/sync/views.view.stanford_person.yml
[SDSS-1431](https://stanfordits.atlassian.net/browse/SDSS-1431) | Edit buttons are shown publicly on people nodes
Removes the 'edit this item' button from the Stanford Person view to prevent it from displaying for unauthorized users.
Verify that the edit content links are not present in the Fields section on the People view here, /admin/structure/views/view/stanford_person
3. Verify...
- Other PRs
- …
=> SDSS-1431: Removed edit button from Stanford Person view.

docroot/profiles/sdss/sdss_profile/modules/stanford_profile_helper/modules/jumpstart_ui/dist/templates/decanter/components/brand-bar/brand-bar.twig
Updated the hardcoded URL in the brand-bar template from https://stanford.edu to https://www.stanford.edu.
1
2. Rebuild cache
3. Verify that the brand-bar's Stanford University link is https://www.stanford.edu.
https://stanfordits.atlassian.net/browse/SDSS-1391
- [Browserstack](https://live.browserstack.com/dashboard) and link to [Browserstack Credentials](https://asconfluence.stanford.edu/confluence/display/S …
=> SDSS-1391: Add 'www' to Stanford University brand bar link

docroot/profiles/sdss/sdss_profile/modules/sdss_news_sharing/sdss_news_sharing.links.menu.yml, docroot/profiles/sdss/sdss_profile/modules/sdss_news_sharing/sdss_news_sharing.routing.yml
Moved the SDSS News Sharing Settings to be a menu link in Importers and changed the route to match.
1. Pull the changes and rebuild cache.
2. Verify that the 'SDSS News Sharing Settings' menu link is no longer listed in the admin toolbar under Configuration->Web Services, and is available under Configuration->Importers.
3. Navigate to /admin/config/importers/sdss-news-sharing and verify that the news sharing form is present.
https://stanfordits.atlassian.net/browse/SDSS-1333
=> SDSS-1333: Move SDSS News Sharing Settings to Configuration->Importers

docroot/sites/settings/global.settings.php
Change the memory limit increase to be during install tasks and not for all drush commands.
See: [SDSS-1442](https://stanfordits.atlassian.net/browse/SDSS-1442): BUG | Provisions failing on Acquia due to Memory Exhaustion error
[SDSS-1442]: https://stanfordits.atlassian.net/browse/SDSS-1442?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SDSS-1442: Change memory limit increase to be during install tasks

docroot/sites/settings/global.settings.php
Removed inaccurate information from the comment. The memory does not need to be increased in the Cloud UI to handle the limit set in the override.
=> SDSS-1442: Remove inaccurate memory increase comment

docroot/sites/sites.php
Point nzea.stanford.edu to nza instead of neza.stanford.edu
=> SDSS-1477: Point nzea.stanford.edu to nza instead of neza.stanford.edu

blt/src/Blt/Plugin/Commands/GryphonHooksCommands.php
- The `field_validation_legacy` module needs to be enabled before database updates run
- The pre-command for the hook I added was incorrect and needed to be changed.
=> SDSS-000: Change code deploy hook for enabling field_validation_legacy module

docroot/profiles/sdss/sdss_profile/config/sync/core.entity_form_display.node.stanford_event.default.yml, docroot/profiles/sdss/sdss_profile/config/sync/core.entity_form_display.node.stanford_news.default.yml, docroot/profiles/sdss/sdss_profile/config/sync/core.entity_form_display.node.stanford_person.default.yml
[SDSS-460](https://stanfordits.atlassian.net/browse/SDSS-460): Enable URL alias editing for News, Events, People
- Enabled the URL alias field on News, Events, and People node forms
[SDSS-460]: https://stanfordits.atlassian.net/browse/SDSS-460?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SDSS-460: Enable the URL alias field on News, Events, and People node forms

docroot/profiles/sdss/sdss_profile/config/sync/views.view.stanford_events.yml
[SDSS-1496](https://stanfordits.atlassian.net/browse/SDSS-1496): Add additional vocabularies to Past Events list display filter
- Added more vocabularies to the Past Events list paragraph display: Event Audience, Focal Areas, Event Departments & Groups, Event Keywords and Tags, Event Subject
[SDSS-1496]: https://stanfordits.atlassian.net/browse/SDSS-1496?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SDSS-1496: Add more filters to Past Events list paragraph

docroot/sites/sites.php
Point [integrative-design-for-radical-energy-efficiency.stanford.edu](http://integrative-design-for-radical-energy-efficiency.stanford.edu/) to `extreme_energy_efficiency` site.
=> Point integrative-design long alias to extreme energy efficiency site

.github/workflows/copy_dbs_to_staging.yml, README.md, docs/architecture/decisions/0000-record-architecture-decisions.md, docs/architecture/decisions/0001-automate-database-copy-updates.md, hooks/common/post-db-copy/post-db-copy.sh
- Added code in `post-db-copy` cloud hook to run updates on a site after database has been copied.
- Added Github actions workflow to copy production databases to staging. This workflow is triggered manually from the Actions tab on Github.
- Currently copying databases down from production to staging and then running updates across all staging sites were manual and time consuming processes for a developer. With these changes, the developer only needs to trigger the workflow and Github will do the rest.
- Also added ADR's to this repo.
=> Added database copying automation and ADR's

docroot/sites/settings/global.settings.php
Adds sdss_workgroup_tagging.settings to config_readonly whitelist to allow live site configuration.
- ASAP
=> SDSS-1347: Add Workgroup Tagging settings to config_readonly whitelist

docroot/profiles/sdss/sdss_profile/config/sync/core.entity_form_display.paragraph.editorial_sidebar.default.yml, docroot/profiles/sdss/sdss_profile/config/sync/core.entity_view_display.paragraph.editorial_sidebar.default.yml, docroot/profiles/sdss/sdss_profile/config/sync/field.field.paragraph.editorial_sidebar.su_hide_sidebar_title.yml, docroot/profiles/sdss/sdss_profile/config/sync/field.field.paragraph.editorial_sidebar.su_sidebar_title.yml, docroot/profiles/sdss/sdss_profile/config/sync/field.storage.paragraph.su_hide_sidebar_title.yml, docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/templates/components/newsroom-sidebar/paragraph--editorial-sidebar.html.twig
[SDSS-856](https://stanfordits.atlassian.net/browse/SDSS-856): Add option to Editorial Sidebar to hide the title
- Added a field to conditionally hide the editorial sidebar title.
- Added help text to inform the user on the importance of adding a relevant title, even if it won't be display visually.
[SDSS-856]: https://stanfordits.atlassian.net/browse/SDSS-856?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SDSS-856: Add field to conditionally hide the editorial sidebar title

docroot/profiles/sdss/sdss_profile/config/sync/field.field.config_pages.stanford_saml.su_simplesaml_roles.yml, docroot/profiles/sdss/sdss_profile/sdss_profile.install, docroot/profiles/sdss/sdss_profile/tests/codeception/acceptance/Users/RoleMappingsCest.php
This PR ensures that the `sdss:webdev` workgroup is mapped to the `administrator` role for all sites using the sdss_profile.
- Adds a database update to append the mapping for existing sites.
- Updates the default value for new installs.
- Adds an acceptance test to verify both `uit:sws` and `sdss:webdev` mappings are present on the SAML config page.
- 7/10: Affects all sites using sdss_profile and SAML role mapping.
1. Check out this branch.
2. Run `drush updb` and confirm no errors.
3. Log in as an administrator and visit `/admin/config/people/stanford-saml`.
4. Confirm both `uit:sws` and `sdss:webdev` mappings are present.
5. Run Codeception acceptance tests and confirm the new test passes.
6. (Optional) Install a new site and confirm both mappings are present by default.
- All sites …
=> SDSS-1539: Map sdss:webdev Workgroup to Administrator Role for All Sites

docroot/profiles/sdss/sdss_profile/config/sync/views.view.events_feeds.yml
The Events XML feed used for calendaring in Smartsheet was broken due to pulling too many events (no filter). Aaron updated the view on the dev site to add a date filter, so events older than 1 year no longer appear. This PR updates the configuration in the codebase.
- 6/10. This affects the sustainability site calendar integration with Smartsheet.
2. Import the updated configuration
3. Verify that the events feed at `/admin/structure/views/view/events_feeds` only shows events from the past year
[SDSS-1542](https://stanfordits.atlassian.net/browse/SDSS-1542): Events XML feed is broken
[SDSS-1542]: https://stanfordits.atlassian.net/browse/SDSS-1542?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SDSS-1542: Update events XML feed

docs/new-site-provision.md
- Updates provisioning documentation to remove the step for creating a cron job per site. This reflects the change in SDSS-1530, where a script now runs Drupal cron across all sites, eliminating the need for individual site cron jobs.
- As soon as possible; no strict deadline.
- 3/10. This affects documentation only and does not impact site functionality.
1. Check out this branch.
2. Navigate to the updated provisioning documentation.
3. Verify that the step to create a cron job for each site has been removed.
[SDSS-1530](https://stanfordits.atlassian.net/browse/SDSS-1530): Add custom Scheduled Cron Job for Scheduler Job
[SDSS-1530]: https://stanfordits.atlassian.net/browse/SDSS-1530?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SDSS-1530: Remove cron job step from provision documentation

docroot/profiles/sdss/sdss_profile/themes/sdss_subtheme/js/scripts.js
[SDSS-1523](https://stanfordits.atlassian.net/browse/SDSS-1523): A11Y: Pause button on home video needs alt text
- Adds dynamic aria-labels to the video banner play/pause button for improved accessibility. The label now updates to "Play video" or "Pause video" based on the button state.
- As soon as possible for accessibility compliance.
- 6/10. Improves accessibility for all users, especially those using screen readers.
2. Sync the sustainability site locally
3. Navigate to the home page of the local Sustainability site
4. Verify the play/pause button updates its aria-label to "Play video" or "Pause video" as appropriate
[SDSS-1523]: https://stanfordits.atlassian.net/browse/SDSS-1523?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWN …
=> SDSS-1523: Add aria-label to the video banner play and pause button
